#!/usr/bin/env php
<?php
	$lineNumber = 1;
	$searchBy = getopt("a:e:t:d:s:m:");
	exec('git log --pretty="%H - %an - %ae - %cd - %s"', $gitLogLines);
	$optionName = array ("hash", "name", "email", "date", "message");
	$commits = array();
	
	foreach ($gitLogLines as $line) {
			$commits[] = array_combine ( $optionName, explode ( " - ", $line) );
	}

	foreach ($commits as $commitOptionName => $comitOptionValue) {
		if (isset($searchBy["a"]) && stripos($comitOptionValue["name"], $searchBy["a"]) === False) {
			$results["Author"] = $searchBy["a"];
			unset($commits[$commitOptionName]);
		}
		if ( isset($searchBy["e"]) && stripos($comitOptionValue["email"], $searchBy["e"]) === False ) {
			$results["Email address"] = $searchBy["e"];
			unset($commits[$commitOptionName]);
		}
		if ( isset($searchBy["t"]) || isset($searchBy["d"]) || isset($searchBy["s"]) ){
			$commitDate = $comitOptionValue["date"] ;
			$commitDate = date_create_from_format("D M j G:i:s Y O", $commitDate);

			if( isset($searchBy["t"]) && $searchBy["t"] !== ($time = date_format($commitDate,"H:i") ) ){
				$results["Time"] = $searchBy["t"];
				unset($commits[$commitOptionName]);
			}
			if ( isset($searchBy["d"]) && $searchBy["d"] !== ($date = date_format($commitDate,"d-m-Y") ) ) {
				$results["Date"] = $searchBy["d"];
				unset($commits[$commitOptionName]);
			}
			if ( isset($searchBy["s"]) && $searchBy["s"] !== ($timestamp = date_format($commitDate,"U") ) ) {
				$results["Epoch Timestamp"] = $searchBy["s"];
				unset($commits[$commitOptionName]);
			}
		}
		if ( isset($searchBy["m"]) && stripos($comitOptionValue["message"], $searchBy["m"]) === False ) {
			$results["Commit Message"] = $searchBy["m"];
			unset($commits[$commitOptionName]);
		}
	}	
	
	foreach ($commits as $commitOptionName => $commitOptionValue) {
		unset( $commits[$commitOptionName]["email"] );
	}

	foreach ($commits as $commitOption) {
		echo "$lineNumber:: ".implode(" - ", $commitOption)."\n";
		$lineNumber++;
	}
?>