#!/usr/bin/env php
<?php
	exec('git log --pretty="%H - %an - %ae - %ad - %s"', $gitLogLines);


	$fields = array ("hash", "name", "email", "date", "message");
	$array = array();
	foreach ($gitLogLines as $value) {
			$array[] = array_combine ( $fields, explode ( " - ", $value) );
	}

	foreach ($array as $value) {
			$value[""] = array_combine ( $fields, explode ( " - ", $value) );
	}	
		
	var_dump($array);

$options = getopt("aetdsm");
if ( isset($options["a"])){

}

if ( isset($options["e"])){
	
}

if ( isset($options["t"])){
	
}

if ( isset($options["d"])){
	
}

if ( isset($options["s"])){
	
}

if ( isset($options["m"])){
	
}


?>






