#!/usr/bin/env php
<?php
class Table {
    private $databaseName;
    private $tableName;
    private $columns;

    function __construct($databaseName, $tableName, $columnsArray = array()) {
        $this->databaseName = $databaseName;
        $this->tableName = $tableName;
        $this->columns = $columnsArray;
    }
    function create() {
        if (file_exists(
            $this->databaseName.DIRECTORY_SEPARATOR.$this->tableName)) {
            echo "Table \"{$this->tableName}\" already exist\n";
        } else {
            $file = $this->databaseName.DIRECTORY_SEPARATOR.$this->tableName;
            $table = fopen($file, 'w');
            fputcsv($table, $this->columns);
            fclose($table);
            echo "\"{$this->tableName}\" CREATED\n";
            return $this->open();
        }
    }
    function open() {
        if (file_exists(
            $this->databaseName.DIRECTORY_SEPARATOR.$this->tableName)) {
            return $this->databaseName.DIRECTORY_SEPARATOR.$this->tableName;
        } else {
            echo "\"{$this->tableName}\" not exist\n";
        }
    }
}
?>